services:
  customer-db:
    image: postgres:16
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    # host:container
    volumes:
      - customer_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # (opcional, já preparando os próximos)
  # transaction-db:
  #   image: postgres:16
  #   container_name: transaction-db
  #   environment:
  #     POSTGRES_DB: transaction_db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5433:5433"
  #   command: ["postgres", "-p", "5433"]
  #   volumes:
  #     - transaction_data:/var/lib/postgresql/data

  # statement-db:
  #   image: postgres:16
  #   container_name: statement-db
  #   environment:
  #     POSTGRES_DB: statement_db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5434:5434"
  #   command: ["postgres", "-p", "5434"]
  #   volumes:
  #     - statement_data:/var/lib/postgresql/data

volumes:
  customer_data:
  # transaction_data:
  # statement_data:
